# Travis file for running some basic set of testreport checks on each commit
services: 
 - docker
 
before_install:
 - docker pull mitgcm/testreport-images:fc11-base-20170715
 - docker run  -v `pwd`:/MITgcm --name fc11-testreport -t -d mitgcm/testreport-images:fc11-base-20170715 /bin/bash
 - docker exec -i fc11-testreport rpm -vv --rebuilddb
 - docker exec -i fc11-testreport df -h
 - docker exec -i fc11-testreport ls -altr /MITgcm
 - docker exec -i fc11-testreport yum install python-pip
 - docker exec -i fc11-testreport yum install gcc-gfortran
 - docker exec -i fc11-testreport yum install python-argparse

script: 
 - echo `pwd`
 # tutorial advection in gyre
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport -t tutorial_advection_in_gyre | tee tutorial_advection_in_gyre/testreport_out.txt"
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; python verification_parser.py -filename 'tutorial_advection_in_gyre/testreport_out.txt' -threshold 16"
 # tutorial baroclinic gyre
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport -t tutorial_baroclinic_gyre | tee tutorial_baroclinic_gyre/testreport_out.txt"
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; python verification_parser.py -filename 'tutorial_baroclinic_gyre/testreport_out.txt' -threshold 14"
 # tutorial barotropic gyre
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport -t tutorial_barotropic_gyre | tee tutorial_barotropic_gyre/testreport_out.txt"
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; python verification_parser.py -filename 'tutorial_barotropic_gyre/testreport_out.txt' -threshold 16"
 # tutorial cfc offline
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport -t tutorial_cfc_offline | tee tutorial_cfc_offline/testreport_out.txt"
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; python verification_parser.py -filename 'tutorial_cfc_offline/testreport_out.txt' -threshold 16"
 # tutorial deep convection
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport -t tutorial_deep_convection | tee tutorial_deep_convection/testreport_out.txt"
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; python verification_parser.py -filename 'tutorial_deep_convection/testreport_out.txt' -threshold 16 16"
 # tutorial global oce biogeo
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport -t tutorial_global_oce_biogeo | tee tutorial_global_oce_biogeo/testreport_out.txt"
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; python verification_parser.py -filename 'tutorial_global_oce_biogeo/testreport_out.txt' -threshold 16"
 # tutorial global oce in p
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport -t tutorial_global_oce_in_p | tee tutorial_global_oce_in_p/testreport_out.txt"
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; python verification_parser.py -filename 'tutorial_global_oce_in_p/testreport_out.txt' -threshold 16"
 # tutorial global oce lat lon
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport -t tutorial_global_oce_latlon | tee tutorial_global_oce_latlon/testreport_out.txt"
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; python verification_parser.py -filename 'tutorial_global_oce_latlon/testreport_out.txt' -threshold 16"
